### ISSUE TITLE
Create ticket (attendee) model

### ISSUE THREAD

**Issue by ricco386** [pyconsk/django-konfera#10]
Create model file:

type: ForeignKey, #9 ticket_type table, NOT NULL
discount_code: ForeignKey, #11 discount_codes table, DEFAULT NULL
status: CHOICES (requested, registered, checked-in, cancelled)
first_name: CharField, max=128
last_name: CharField, max=128
email: EmailField
phone: CharField, max=64
description: TextField
order: ForeignKey, #12 order table, NOT NULL

Once finished, please cross the issue off in list stored at #1 Create initial DB models and migrations

**Comment by TomasHo** [comment]
working on it

**Comment by ricco386** [comment]
please rename the file to ticket.py

**Comment by ricco386** [comment]
MR approved
