### ISSUE TITLE
Remove null=True from text fields

### ISSUE THREAD

**Issue by ricco386** [pyconsk/django-konfera#100]
Avoid using null on string-based fields such as CharField and TextField because empty string values will always be stored as empty strings, not as NULL. If a string-based field has null=True, that means it has two possible values for “no data”: NULL, and the empty string. In most cases, it’s redundant to have two possible values for “no data;” the Django convention is to use the empty string, not NULL.

**Comment by bolyesz** [comment]
working on it :)

**Comment by ricco386** [comment]
@bolyesz thanks PR is in master
