### ISSUE TITLE
Release party for 0.1

### ISSUE THREAD

**Issue by jangondol** [pyconsk/django-konfera#107]
Hi @pyconsk/volunteers, our new Django project is nearing its first ever release, `0.1`. Time to celebrate, right? @ricco386, let's open champagne or at least [Club-Mate](https://en.wikipedia.org/wiki/Club-Mate) at our upcoming meetup... Other celebration ideas welcome... ;-)

**Comment by ricco386** [comment]
:+1:

**Comment by ricco386** [comment]
We will do the release at [meetup](https://2016.pycon.sk/sk/ba-14-meetup.html) today.

I will try to get some refreshments :beer:
