### ISSUE TITLE
Create discount_codes model:

### ISSUE THREAD

**Issue by ricco386** [pyconsk/django-konfera#11]
Create model file:

title: CharField, max=128
hash: CharField, max=64
discount: IntegerField, max=100, min=0
available_from: DateTimeField
available_to: DateTimeField
usage: IntegerField
ticket_type: ForeignKey, #9 ticket_type table, NOT NULL

Once finished, please cross the issue off in list stored at #1 Create initial DB models and migrations

**Comment by TomasHo** [comment]
Working on this

**Comment by ricco386** [comment]
@TomasHo thanks code has been merged.
