### ISSUE TITLE
Social media for events

### ISSUE THREAD

**Issue by ZoltanOnody** [pyconsk/django-konfera#110]
# Original issue

Updte event model with new field: social_media_meta and social_media_list both should be JSONField and it is not required. We will store different social media types in json. I will create another issue with structure of json and how we will display the data.

This will give us flexibility to have different social medias per event and also flexibility in which social media will be used.

Update admin to filed list with new section social_media, that will be hidden by default, and will contain both new fields.
# Edit

JSONField comes with a lot of dependencies such as `postgres` & `django 1.9+`. If you have a better idea how to do it, suggestions are welcome.

**Comment by Redpoint1** [comment]
I will take this issue. I create new field type JSONField.

**Comment by ZoltanOnody** [comment]
> I will take this issue. I create new field type JSONField.

`JSONField` is postgresql specific so I am not sure that's the way we want to go.  @ricco386 ?

**Comment by Redpoint1** [comment]
ooops *similar to JSONField

**Comment by simonsmiley** [comment]
Why not just create a new model for social media with whatever fields are required and use a use then either use foreign keys in the new model or create a many-to-many mapping

**Comment by ricco386** [comment]
@simonsmiley well the thing is that we dont know what social media will be used for event, and they do differ between each other. Sample:
```
  <meta property="og:type" content="website">
  <meta property="og:image" content="https://2016.pycon.sk/static/images/logo/pycon_sk_logo200_notext.png">
  <meta property="og:url" content="https://2016.pycon.sk/en">
  <meta property="og:title" content="PyCon SK 2016 - 11-13.03.2016, Bratislava">
  <meta property="og:site_name" content="2016.pycon.sk">
  <meta property="og:description" content="PyCon SK is a community-organized conference for the Python programming language, which was held in Bratislava on 11th - 13th March, 2016.">
  <meta name="twitter:card" content="summary">
  <meta name="twitter:site" content="@pyconsk">
  <meta name="twitter:title" content="PyCon SK 2016 - 11-13.03.2016, Bratislava">
  <meta name="twitter:description" content="PyCon SK is a community-organized conference for the Python programming language, which was held in Bratislava on 11th - 13th March, 2016.">
  <meta name="twitter:url" content="https://2016.pycon.sk/en">
  <meta name="twitter:image" content="https://2016.pycon.sk/static/images/logo/pycon_sk_logo200_notext.png">
```
Besides we will use JSONField like in payments and there is the same situation again, many provides each requireing different data. Since we dont know them in advance we can not create fixed structure (as DB one) and we can use benefits of json flexibility.

**Comment by simonsmiley** [comment]
in that case probably just a textfield where the json is stored manually as a string

**Comment by ricco386** [comment]
@simonsmiley yes that is the idea behind *JSONField like*, that will have encode and decode for json and some basic validation. It is not explained here properly but I already had a chat with @Redpoint1 about it.
