### ISSUE TITLE
Speaker model country field change to dropdown

### ISSUE THREAD

**Issue by ricco386** [pyconsk/django-konfera#116]
Since there is limited amount of countries, change it to dropdown with list (everywhere, forms, admin, etc...) of all countries, and SK predefined value.

**Comment by ricco386** [comment]
@abhishekg785 how it is going? Do you need more info, with regards this issue?

**Comment by sourabh1024** [comment]
What do you mean by SK predefined value ?

**Comment by ZoltanOnody** [comment]
Slovakia should be the default country.

**Comment by sourabh1024** [comment]
Also , is there any predefined list of countries, which dropdown should have ?

**Comment by ricco386** [comment]
create file countries.py and add translatable constants:

SLOVAK_REPUBLIC = 'SK'
CZECH_REPUBLIC = 'CZ'

COUNTRIES = (
    (SLOVAK_REPUBLIC, _('Slovak Republic')),
    (CZECH_REPUBLIC, _('Czech Republic')),
)

This way we can import COUNTRIES as a choice field in any model... List of all countries in the world, can be found for example here: https://www.countries-ofthe-world.com/all-countries.html

**Comment by jangondol** [comment]
@ricco386 Standard list of countries + country codes: [ISO 3166-1](https://en.wikipedia.org/wiki/ISO_3166-1).

**Comment by ricco386** [comment]
thanks @jangondol I just got the first link from google :smile: this list make the issue easier, as there is the alpha-2 code.

**Comment by ZoltanOnody** [comment]
done in #159
