### ISSUE TITLE
Create order model

### ISSUE THREAD

**Issue by ricco386** [pyconsk/django-konfera#12]
Create model file:

price: DecimalField
discount: IntegerField
status: CHOICES (awaiting payment, paid, expired, cancelled)
purchase_date: DateTimeField
paiment_date: DateTimeField

Once finished, please cross the issue off in list stored at #1 Create initial DB models and migrations

**Comment by kisso** [comment]
obsadene

**Comment by ZoltanOnody** [comment]
done in https://github.com/pyconsk/django-konfera/pull/32 close it

**Comment by ricco386** [comment]
@kisso @ZoltanOnody thank you guys closing the issue.

**Comment by TomasHo** [comment]
@ricco386 @ZoltanOnody what is the idea of order.discount here pls ? Do we want to have discount codes + per order discount too ?

**Comment by ricco386** [comment]
@TomasHo order is an aggregator of tickets, so lets say company wants to send 10 people to the conference, they do not want to have 10 tickets and 10 receipts, instead they want just one.

If 2 from this people have an discount codes they can apply them on their tickets and in the order there is aggregated price for all 10 people, and also aggregated discount. This allows us to have multiple ticket types in that order and also multiple discount codes, also with different percentage discount per ticket.

How ever in the order discount should be DecimalField as it will store amount in currency not percentage as it does in dicount_codes table. Similar it is with price, ticket_type, has price but we store it again in order, this way even if we change the price it ticket_type it doesnt changes on already sold tickets and price will match the reality they have paid.

There was an error in schema i drew, and I have already fiexed it, thanks for spotting it.
