### ISSUE TITLE
volunteers registration (view and form) updates

### ISSUE THREAD

**Issue by ricco386** [pyconsk/django-konfera#120]
view updates:
 * after storing data in DB  show successful message
 * make sure ticket_type is public

form updates:
 * Make description field required.
 * Add help text for description: Please tell us something about yourself.

**Comment by ricco386** [comment]
Once you are at it please also do this improovments:

In view, please get rid of the if request.method == "POST" line with form = VolunteerRegistrationForm(request.POST or None) this way we can get rid of one if statement so the code is easier to read (more if statement worse Cyclomatic complexity score results). See cfp_form_view as an example.

In template update the button to be nicer and uses Bootstrap styling. See egistration_form.html as an example.

**Comment by ricco386** [comment]
There is an issue #125 that changes the directory structure to avoid conflicts, lets do the parent issue first.

**Comment by andela-ijubril** [comment]
Hi @ricco386, I would like to takea shot at this.

**Comment by ricco386** [comment]
Hello @andela-ijubril sure go ahead. If you need more info or something is not clear just ask. Thanks

**Comment by andela-ijubril** [comment]
Hi @ricco386, I need more info on this issue. Thanks

**Comment by ricco386** [comment]
PR #130 has been closed thanks @andela-ijubril
