### ISSUE TITLE
private registration view

### ISSUE THREAD

**Issue by ricco386** [pyconsk/django-konfera#122]
Add a view that will check uuid in the url, based on this uuid form for ticket is rendered.
 
* Make sure TicketType UUID get from url and ACCESSIBILITY is Private
* TicketType has to be in available date range
* ticket with price is in requested state, everyone else in state registered
* Those in requested state have description required field in the form

**Comment by ricco386** [comment]
There is an issue #125 that changes the directory structure to avoid conflicts, lets do the parent issue first.

**Comment by ZoltanOnody** [comment]
I'll do it

**Comment by ZoltanOnody** [comment]
Unfortunately I don't have time to finish it this week.

**Comment by simonsmiley** [comment]
@ricco386, @ZoltanOnody I just submited a pr. I didn't get all of what was required, but I guess most of my merge request makes sense. I guess it would be possible to improve it, but that can be discussed there rather than here :-)

**Comment by ricco386** [comment]
@simonsmiley thanks, I have explained everything needed in the PR #167 I guess it is clear there, but if you have more questions do not hesitate to ask.
