### ISSUE TITLE
Refactor registration to its own module

### ISSUE THREAD

**Issue by ricco386** [pyconsk/django-konfera#125]
I think we will have the pattern of register in multiple views, urls, so lets set it free and move it its own module. This way we should have less conflicts in long run.

Module should looks like this:

konfera
├── admin.py
├── ....
├── register
│   ├── init.py
│ ├── forms.py
│ ├── urls.py
│   └── views.py
├── ....
├── urls.py
├── utils.py
└── views.py

urls in konfera should include everything in module urls, currently we have only `event/(?P<event_slug>[\w, -]+)/register/volunteer/` which I think we should change in `/register/volunteer/event/(?P<event_slug>[\w, -]+)/`. View rendering this url should be moved to module as well, and same goes for the form.

Update also templates directory structure and add register module and move all views into it.

**Comment by ricco386** [comment]
To avoid conflicts this issue should be done before #122 and #123 that suggests more registration improovements.

**Comment by Sb8691** [comment]
OK i'm taking this task...

**Comment by ricco386** [comment]
PR merged
@Sb8691 @kapucko thanks
