### ISSUE TITLE
Refactor list all events

### ISSUE THREAD

**Issue by ricco386** [pyconsk/django-konfera#127]
Update urls to: /events (this is due to UX and ease of remember url for human)

Template look for all events needs a bit polishing, since we have already base template and [bootstrap](https://getbootstrap.com/) and [pycon](https://2016.pycon.sk) stylesheets available. Update [pagination](https://getbootstrap.com/components/#pagination).

List look update to be more like [meetup list](https://2016.pycon.sk/en/meetup.html). Currently list is just list of titles, add also dates and location. Make sure we display only public events here.

**Comment by Matusf** [comment]
Working on it

**Comment by ricco386** [comment]
PR merged
