### ISSUE TITLE
Create receipt model

### ISSUE THREAD

**Issue by ricco386** [pyconsk/django-konfera#13]
Create model file:

title: CharField, max=128
street: CharField, max=128
street2: CharField, max=128
city: CharField, max=128
postcode: CharField, max=12
state: CharField, max=128
id: CharField, max=32
taxid: CharField, max=32
vatid: CharField, max=32
amount: FloatField

Once finished, please cross the issue off in list stored at #1 Create initial DB models and migrations

**Comment by ZoltanOnody** [comment]
done in https://github.com/pyconsk/django-konfera/pull/28 close it

**Comment by ricco386** [comment]
@mimmon @ZoltanOnody thanks, closing issue.
