### ISSUE TITLE
Create public tickets view

### ISSUE THREAD

**Issue by ricco386** [pyconsk/django-konfera#130]
Add a view that will list all available ticket types, user will be able to select what kind of ticket he would like to register.

**Comment by ricco386** [comment]
There is an issue #125 that changes the directory structure to avoid conflicts, lets do the parent issue first.

**Comment by kapucko** [comment]
@ricco386 Do you want to modify the already existing volunteer registration form? It would be possible to add there dropdown menu with list of all available ticket types for given event. And the url could be /register/event/<event_slug> . That's my idea but maybe you had  something else in your mind.

**Comment by ricco386** [comment]
@kapucko my idea was that we will have a page that will display all tickets, with the description, price, etc... So the user can choose, student or standard or supporter or anything else that will be defined as public ticket... Once user select ticket he will just click on the link type and on second page form will be presented where he fills the details.

So you can modify volunteer registration form, but instead of dropdown there will be hidden field. So far is seems to me that we will have only two form types, one for public tickets, that doesn have to have description field and private tickets, that will have description required. This seems to be good enought for version 0.2 in the near future we can have thoughts how to improove so you can set any field required per ticket type.

**Comment by andela-ijubril** [comment]
Is anyone working on this?
I would like to give this a shot.

**Comment by kapucko** [comment]
@andela-ijubril I haven't started yet, so you can take it.

**Comment by ricco386** [comment]
@kapucko if you have time you can carry on with this issue, and @andela-ijubril can do the issue #120 Thanks guys...

**Comment by kapucko** [comment]
Ok :)

**Comment by kapucko** [comment]
In progress...

**Comment by simonsmiley** [comment]
@kapucko are you still working on it?

**Comment by kapucko** [comment]
Yes I'm

**Comment by ricco386** [comment]
PR merged. thanks
