### ISSUE TITLE
Ticket save validation

### ISSUE THREAD

**Issue by ricco386** [pyconsk/django-konfera#148]
Creating ticket allows to store not valid data. If you have multiple ticket types for multiple events and discount codes in multiple events. System does not check if you do not mix discount codes and different events. Update save method to check if discount code belongs to ticket type

**Comment by bambielli** [comment]
I can take a look

**Comment by ricco386** [comment]
@bambielli thanks, if you have question do not hesitate to ask. It would be great if you also provide unittest for your code (it is not required, but we encourage good practice :smile: )

**Comment by bambielli** [comment]
of course!

**Comment by bambielli** [comment]
After speaking with @ricco386, we decided to put the validation logic in the ticket model save method. Validation logic like this definitely belongs in the model, not in the view, and the model can raise a validationerror with text that gets passed back to the order view.

Expected Implementation:

For the ticket being saved, check to see if the ticket_type for the selected discount_code is the same as the ticket_type for the ticket being saved. 
  - If the ticket_types are the same, validation is successful
  - If the ticket_types are not the same, that indicates the discount code is not applicable for the selected ticket type, and a validation error should be raised.
