### ISSUE TITLE
Update Order save function

### ISSUE THREAD

**Issue by ricco386** [pyconsk/django-konfera#149]
Currently if we create order via admin we can and add multiple tickets. Update order save method to re-calculate price and discount for all tickets together.

**Comment by yash2696** [comment]
I want to try this..

**Comment by andela-ijubril** [comment]
Hi @yash2696 still on this?

**Comment by ZoltanOnody** [comment]
@andela-ijubril I think you can do it if you are still interested in it :)

**Comment by simonsmiley** [comment]
@andela-ijubril Do you still want to work on it?

If the price and discount fields for the order are automatically generated, could they be dropped from the model and replaced with a property? That would make them always reflect the current status.
Should the discount be the total discount offered on the order in currency units?

**Comment by andela-ijubril** [comment]
@simonsmiley You can go ahead with it.

**Comment by ricco386** [comment]
@simonsmiley unfortunately they can not be replaced with property. Reason for that is that if you have order it means ticket is issued, and if someone changed the ticket_type price it would also change data in history. We want to avoid it, and price on order should reflect received amount of money at all times, no matter what change happen on other places.
The answer to your second question is Yes, discount should be total discount for whole order in currency units.

**Comment by ricco386** [comment]
PR #208 has been merged.
