### ISSUE TITLE
Update schedule model validation

### ISSUE THREAD

**Issue by ricco386** [pyconsk/django-konfera#156]
When storing schedule model add clean and save methods (see ticket for inspiration), that will do the following validation:
- Only approved talk can be scheduled
- If talk is selected duration is copied from talk
- Event is related to location and location has room, make sure selected room in schedule belongs to Event's location
- Make sure date and time is within the event's range
- Make sure system does not allow store two events at the same time in the same room, eg. schedule datetime + duration in room is unique.

**Comment by masterp4dev** [comment]
Hi @ricco386, I would like to try this.

**Comment by ricco386** [comment]
Hi @masterp4dev sure go ahead...

**Comment by ZoltanOnody** [comment]
Hey @masterp4dev how is it going? If you need any advice, feel free to ask.

**Comment by EmilLuta** [comment]
Hello guys. I'm not sure on how the current progress is going, but I was wondering if I could give it a go. What do you think?

**Comment by ZoltanOnody** [comment]
@EmilLuta sure :)

**Comment by EmilLuta** [comment]
@ZoltanOnody Seems like I'll have to drop this one, sadly. Feel free to reassign it to someone else.

**Comment by ricco386** [comment]
PR #212

**Comment by ricco386** [comment]
we shall leave as it is and focus on #291
