### ISSUE TITLE
Ticket's discount code usage

### ISSUE THREAD

**Issue by ricco386** [pyconsk/django-konfera#157]
Once ticket is saved, and if discount code is applied, make sure we do not have more discounted tickets, than allowed usage defined in discount code.

**Comment by mimmon** [comment]
I'll take this.

**Comment by mimmon** [comment]
Do we need to keep track of when has the discount code been applied in separate place or is it enough to simply subtract from usage?

**Comment by ricco386** [comment]
Write a method that will do a search for discount codes, eg. how many times it was used. During ticket save (in clean method) call your new method and compare result with usage, if it should exceed the usage raise validation error.

**Comment by mimmon** [comment]
Sorry, I've found your instructions too late. I've already made a pull request. Although, it seems to me that my contribution is pretty close to your instructions and also it worked during my tests, I will appreciate if you let me know if there are some flaws or a way to better follow the Django's best practices.

**Comment by ricco386** [comment]
PR #165 has been merged
