### ISSUE TITLE
Create list speakers view

### ISSUE THREAD

**Issue by ricco386** [pyconsk/django-konfera#16]
Create simple view (with template) that will list all speakers (for the event) in the DB order alphavetcaly by last name.

**Comment by TomasHo** [comment]
working on this

**Comment by TomasHo** [comment]
At the moment Speaker in not related to Event, just Sponsor. Should we introduce a Many2Many field at this point?

**Comment by ricco386** [comment]
no need for that, speaker has to have talk, and talk is tied to event.

So if you filter all talks for event and than you can access all the speakers, use can use select related, we have discussed earlier.

**Comment by ricco386** [comment]
PR merged into master
