### ISSUE TITLE
Update constants in all models

### ISSUE THREAD

**Issue by ricco386** [pyconsk/django-konfera#161]
Currently we have constants outside the models class:

```python
CONFERENCE = 'conference'
MEETUP = 'meetup'

EVENT_TYPE_CHOICES = (
    (CONFERENCE, _('Conference')),
    (MEETUP, _('Meetup')),
)

DRAFT = 'draft'
PUBLISHED = 'published'
PRIVATE = 'private'
EXPIRED = 'expired'

EVENT_STATUS_CHOICES = (
    (DRAFT, _('Draft')),
    (PUBLISHED, _('Published')),
    (PRIVATE, _('Private')),
    (EXPIRED, _('Expired')),
)


class Event(FromToModel):
    title = models.CharField(verbose_name=_('Event name'), max_length=128)
    slug = models.SlugField(verbose_name=_('Event url'), help_text=_('Slug field, relative URL to the event.'))
    description = models.TextField(blank=True)
```

move all constants inside the class:

```python
class Event(FromToModel):
    CONFERENCE = 'conference'
    MEETUP = 'meetup'
```

this way we can import just Event and access class Event.MEETUP, instead of extra import. Besides this is according Django documentation.

Please go through all models and fix also const usage in models.

**Comment by minibhati93** [comment]
Hi @ricco386 . I am a beginner in Django. Can I still try this ?

**Comment by ricco386** [comment]
Hello @minibhati93, yes this is really easy issue, and it is suitable for beginner. 

Try to setup the project as it is explained in the example readme. And once it is up and running just go through all models and move constants into classes. You will also need to go through all other files and check if we are importing constants and import class instead and update the code.

**Comment by ricco386** [comment]
@minibhati93 seems there is already PR #162 for this issue, but dont worry I will create few more very soon...

**Comment by ZoltanOnody** [comment]
@PKpacheco we would appreciate if in the future you signed up for an issue by leaving a comment. It prevents the situation where 2 people work on the same thing. :)

**Comment by ricco386** [comment]
@Matusf thank you PR has been merged.
