### ISSUE TITLE
Update fixtures

### ISSUE THREAD

**Issue by ricco386** [pyconsk/django-konfera#171]
Update fixture (konfera/fixtures/test_data.json) to have all the data from PyCon SK 2016 (and also meetups). You can find all data at webpage: https://2016.pycon.sk

Easies way is to update data, via admin and than dump them: `./manage.py dumpdata --indent=2 > konfera/fixtures/test_data.json`

**Comment by arruda** [comment]
Hi there, just landed in this project, so I'm a bit lost. Could you point out exactly what are the data that you want from the  https://2016.pycon.sk?
Or what are the django models that will be used, so that I can understand a bit more of what is needed in this update =)?

**Comment by arruda** [comment]
Just to see if I got the idea of this issue, the models you want to add more fixtures to are this:

* Event (Location, Sponsors)
* Schedule (Room, Talk, Speaker)

And this should be got not only from the Pycon SK 2016 event, but also from the meetup page, right?

**Comment by arruda** [comment]
Sorry for the huge amount of questions, but regarding the sponsors of PyconSK, in the event page There are also some that appear under the labels `Main media partner`, `Media partners`, `Partners Conference` and also the `Supporters of the conference` part. This ones should also be added to the fixtures under `Other` sponsor type?

Not all the Supporters of the conference have the required fields for been saved as a Sponsor.

**Comment by ricco386** [comment]
@arruda no problem, I should better defined the task...

`http://127.0.0.1:8000/admin/konfera/event/` (type meetup): https://2016.pycon.sk/en/meetup.html (fixture already contains 11 of them)
`http://127.0.0.1:8000/admin/konfera/speaker/`: https://2016.pycon.sk/en/speakers.html (fixture already contains 4 of them, for email use: privateX@example.com, dont worry about sponsor relation)
`http://127.0.0.1:8000/admin/konfera/talk/`: https://2016.pycon.sk/en/schedule-friday.html and https://2016.pycon.sk/en/schedule-saturday.html (fixture already contains 4 of them for already defined speakers)
`http://127.0.0.1:8000/admin/konfera/sponsor/`: https://2016.pycon.sk/en/sponsors.html (dont worry about the logo, you can upload any picture just use sponsor.svg name), those that does not match add under other section and you can ignore supporters.

You dont need to wrry about schedule as I want to create an issue for generating the data there.

Hope this makes it clear, however if you have any other question do not hesitate to ask.

**Comment by arruda** [comment]
I see, I'll get into it then =)
Thanks
