### ISSUE TITLE
Add views for aid and press registration

### ISSUE THREAD

**Issue by ricco386** [pyconsk/django-konfera#172]
We have view for registering volunteers, but we also need similar view for registering press and people who got tickets by us.

Add two more views `register_aid` and `register_press` similar to `register_volunteer` they all should use the same code base (create generic function that will use all 3 views and we will change just attendee_type).

**Comment by Battleroid** [comment]
If it's alright with you I'd like to give this a try.

**Comment by ricco386** [comment]
@Battleroid sure go ahead. Thanks.

**Comment by Battleroid** [comment]
How can I test the registration for a given sample event (e.g. an event with a slug of 'test')? I just want to make sure it works before I submit my changes.

**Comment by mimmon** [comment]
I'll take care of this.

**Comment by ricco386** [comment]
Seems this is already there, we just forgot to close the issue.
