### ISSUE TITLE
Display order

### ISSUE THREAD

**Issue by ricco386** [pyconsk/django-konfera#173]
Add new view that will display order details.

Once ticket is saved, redirect to show order details.

**Comment by iraquitan** [comment]
Hi, I'd like to give it a try. Can you give me some initial details? The ticket is saved through the Orders admin view?

**Comment by ricco386** [comment]
if you open in browser `http://127.0.0.1:8000/register/volunteer/event/2016/` you will see registration page. Once it is filled new ticket is created, ticket automatically generate an order. Purpose of this task is to create view that will display details of this order and update the view that user is redirected to see details of his order.

Order has uuid please use that in url of your new view. For example `/order/(?P<order_uuid>[\w, -]+)/` and it will display details of the order, and also related tickets. Please bear in mind that if order is created in admin it can have multiple tickets.

Hope this helps, if you have more questions, just ask. Thanks.

**Comment by uj00007** [comment]
hey,i was looking into your issue ,but when i ran it ,it gives some error ,i think the apps are placed incorrectly in directories ,then i shifted them in example the it ran ok,the server was established but when i run the server in the browser,there are no pages configured or the opening html page or index.html ..is that ryt.?

**Comment by ZoltanOnody** [comment]
closed in #179
