### ISSUE TITLE
Conferences list

### ISSUE THREAD

**Issue by ricco386** [pyconsk/django-konfera#174]
Currently we have /meetups page that display all meetups. Create a page for conferences that will display conferences only.

**Comment by DeKaN** [comment]
Can I use CBV (Class-based view) for this issue? Is page for conferences should use different template?

**Comment by ricco386** [comment]
@DeKaN currently we have views.py in root directory which contains only meetup_list function. Purpose of this task is to create conferences_list function that will list event_type=CONFERENCE.

Yes you can re-factor to use CBV (Class-based view), for both of this views (your new one and also meetup_list). Please create a generic function that both views will use, so we dont duplicate the code. And yes the each view should have its own template.

If you have more questions do not hesitate to ask. Thanks.

**Comment by DeKaN** [comment]
@ricco386 Is redirect needed for list with one item? You can see first solution in #176

**Comment by ricco386** [comment]
@DeKaN looks good, yes I think it is better UX, why show screen where user doesnt have anything to choose from. Therefore I prefer to redirect to event details if there is only one... I spotted just minor things

**Comment by ricco386** [comment]
PR merged. Thanks.
