### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by ricco386** [pyconsk/django-konfera#18]
On the landing page show list of available events. 
If there is just one event redirect to its details page. 

- [x] #19 Create list events view 
- [x] #17 Show event details view

**Comment by Redpoint1** [comment]
the checkboxes are not checked but tickets are closed ... so the dependencies are solved

**Comment by ricco386** [comment]
@Redpoint1 yes I have updated the issue dependencies as done.

We still need the index page, either display list or details of event...

**Comment by ZoltanOnody** [comment]
I'll do it.

**Comment by ricco386** [comment]
@Redpoint1 @ZoltanOnody thanks PR has been merged to master
