### ISSUE TITLE
tickets must be for same event in order - validation

### ISSUE THREAD

**Issue by ZoltanOnody** [pyconsk/django-konfera#180]
There can be multiple tickets in one order.
We need to validate that each ticket is for the same event.

**Comment by HashCode55** [comment]
Hey, I'd take this one... Can you just give a gist what/where the work needs to be done?

**Comment by DeKaN** [comment]
When you want to validate it?

**Comment by ZoltanOnody** [comment]
Before saving the order.

**Comment by DeKaN** [comment]
I will write code for it

**Comment by DeKaN** [comment]
@ZoltanOnody You can't check this before saving order, only before saving ticket for order.

**Comment by ZoltanOnody** [comment]
Okay, so do it that way if it works.

**Comment by ricco386** [comment]
PR #181 has been merged long time ago, we just forgot to close the issue.
