### ISSUE TITLE
Landing page settings

### ISSUE THREAD

**Issue by ricco386** [pyconsk/django-konfera#187]
Landing page (index) should redirect to one of the pages: latest conference, latest meetup, list of conferences, list of meetups (all this views are already build).

Add setting LANDING_PAGE that will have pre defined const. 'latest_conference' and do the redirect (This is current behaviour). If no conference or meetup is defined in the DB, log warning message and redirect to list.

**Comment by mimmon** [comment]
I will take this one.

**Comment by ricco386** [comment]
Isse has been merged. No need for this issue
