### ISSUE TITLE
generate sitemap.xml

### ISSUE THREAD

**Issue by ricco386** [pyconsk/django-konfera#196]
Add ability to generate [sitemap.xml](https://support.google.com/webmasters/answer/156184?hl=en)

**Comment by ZoltanOnody** [comment]
I just read the *Do I need a sitemap?* part and I am not sure we need it. Is there a particular reason you want to have one?

**Comment by ricco386** [comment]
Sitemap can improove crawling by adding extra meta data (when was the page last updated, how ofter googlebot should return to it, or importance of the page), besides google webmaster tools suggested me to create a sitemap.

I dont think that this has hight priority, first we should generate the navigation. Afterwards we will see if there are some public pages that are not listed in the navigation (which probably wont), we dont break anything if we generate it.

**Comment by ricco386** [comment]
no need to add this in app, Django has already build in functionality for this.

https://docs.djangoproject.com/en/1.10/ref/contrib/sitemaps/
