### ISSUE TITLE
Add new fields to event model

### ISSUE THREAD

**Issue by ricco386** [pyconsk/django-konfera#198]
Add new fields to event model (none of them is required): 
* *cfp_allowed*: Boolean field, default: True, help text: Weather to allow submitting talk proposals.
* *cfp_end*: Datetime field, help text: Call for proposals deadline.
* *contact_email*: EmailField, help text: Publicly displayed email to contact organizers.
* *coc*: TextField, name: Code of Condict
* *coc_phone*: CharField, help text: Publicly displayed phone to contact organizers.
* *coc_phone2*: CharField, help text: Publicly displayed phone to contact organizers.
 
Add validation for the cfp_end field have to be before date_from and required if cfp_allowed.
Update existing cfp view to show 404 if cfp_allowed is False. Once we pass the cfp_end date do not show (allow to submit) form, and display message (Something along this): 

> Thank you for your interest, but unfortunately call for proposals deadline was at: `cfp_end`. However if you feel like you have to submit your talk anyway, feel free to contact us: `contact_email`

Update admin area to be able to update new fields and create a migration for the new fields.

**Comment by mimmon** [comment]
I will take this, if it is not urgent. Please let me know so that I can assign it to myself.

**Comment by ricco386** [comment]
Sure, do it...

**Comment by ricco386** [comment]
@mimmon I have updated issue and moved few fields (coc) into separate issue, as we need it on the site. When I created that bug I totally forgot you already have it here. Sorry about this.
