### ISSUE TITLE
Create events model 

### ISSUE THREAD

**Issue by ricco386** [pyconsk/django-konfera#2]
Create model file:

title: CharField, max=128
description: TextField,
from:  DateTimeField,
to:  DateTimeField,
type: CHOICES, (conference, meetup)
status: CHOICES, (draft, published, expired)
location: ForeignKey, #3 location table

Once finished, please cross the issue off in list stored at #1 Create initial DB models and migrations

**Comment by 16961714b** [comment]
I am working on this model

**Comment by ZoltanOnody** [comment]
done in https://github.com/pyconsk/django-konfera/pull/29 close it

**Comment by ricco386** [comment]
@16961714b @ZoltanOnody thank you guys, closing issue.
