### ISSUE TITLE
Call for proposals view

### ISSUE THREAD

**Issue by ricco386** [pyconsk/django-konfera#20]
Create form for speaker details and also talk details, that can anyone submit and it will store speaker and talk as a draft in the DB.

**Comment by TomasHo** [comment]
Working on this

**Comment by TomasHo** [comment]
@ricco386 I have worked on this a have a question or two.
I've created 2 ModelForms add_speaker & add_talk, separate views.
Question regarding talk form: Having a form where you can list all registered speakers(through FK relation) doesn't seem the right approach. Any suggestions ?

**Comment by ricco386** [comment]
@TomasHo not entrely sure what you mean with:

> Having a form where you can list all registered speakers(through FK relation) doesn't seem the right approach.

My idea was this:

You crate 2 ModelForms, one for speaker, one for talk, but there will be just one view. New view called cfp, or similar (up to you to pick up the name). In this view you render model forms and in the template you will have one, below other. Once the forms rendered by tempaltes are submitted, you pass the data from request to the ModelForms, both of them has to be valid and if so store data in DB and redirect to some thank you view, or better to landing page and show just [message](https://docs.djangoproject.com/en/1.10/ref/contrib/messages/). However if one of the forms is not valid display the view with error message.

Does this make sense?

**Comment by SvetlanaM** [comment]
for this use case , django formsets is very good, if you need implementation advice

**Comment by TomasHo** [comment]
Thank you both, formsets was the thing I was missing :)

**Comment by ricco386** [comment]
I have merged PR. but in the mean time I have found few isses reported in separate bug #97
