### ISSUE TITLE
Update evet with Code of Conduct field

### ISSUE THREAD

**Issue by ricco386** [pyconsk/django-konfera#201]
We need to have a way how to define code of conduct for event. 

Update event model with new text fields (none of them is required):
* *coc*: TextField, name: Code of Condict
* *coc_phone*: CharField, help text: Publicly displayed phone to contact organizers.
* *coc_phone2*: CharField, help text: Publicly displayed phone to contact organizers.
 
Update admin area to be able to edit this new fields and create a migration for the new fields.. 

Add new view: /event_slug/code-of-conduct that will display the content of the event.coc field or 404 if it is empty.

**Comment by mimmon** [comment]
I'll take this as it is related to #198

**Comment by ZoltanOnody** [comment]
@mimmon I appreciate your effort but I'd be happy if you could finish the previous issues before assigning yourself new one. Currently you have assigned 4 issues and there is only one PR. The problem is that if someone else would like to contribute as well, he couldn't, because most of them are already assigned.

**Comment by jbub** [comment]
I'll give it a go then

**Comment by ricco386** [comment]
sorry guys this is my fault I totally forgot we already had this requirement in issue #198 

Lets do it this way:
@ZoltanOnody is right that everyone should have assigned one task and when it is submited for review that he can pick up next one. Therefore I think @jbub should do this issue.

I have updated this bug to have everything related to CoC and @mimmon your bug will have bit about CfP. However you both are working on same model, so second one who will have aprooved PR, will most probably have to resolve the conflict.

**Comment by ricco386** [comment]
seems that @mimmon already updated the model in issue #198 and submitter pull request #202 so I am closing this bug as we will finish it there... One more time sorry @jbub for the confusion...
