### ISSUE TITLE
Order receipt form

### ISSUE THREAD

**Issue by ricco386** [pyconsk/django-konfera#203]
Whoever purchase a ticket should be able to fill in billing details. We store them in receipt table, this table is linked to order. Update order view (order/<uuid>/) to be able to fill the receipt section.

By default after purchase order is in  awaiting payment state (status), only in this state allow to modify receipt. On the view we should see a form for receipt, that can bu submited and it would modify the receipt values in DB (can be submitted ulimited times in status awaiting_payment, in other status form should  not be editable). Crete a model form and display it on this view, and store in DB once posted by user.

To get to the order page, you have to have ticket_type availeble (beaware of date checks to display tickets). On /tickets page you can select a active ticket you are purchasing and you will be redirected to order page (and we need to modify this one).

**Comment by mimmon** [comment]
I would like to try this one.

**Comment by ricco386** [comment]
PR  merged
