### ISSUE TITLE
Add new model Organizer

### ISSUE THREAD

**Issue by ricco386** [pyconsk/django-konfera#204]
Add new model organizer, model should have following fields:

* title - char 128 (required)
* street - char 128
* street2 - char 128
* city - char 128
* postcode - char 12
* state  - choice COUNTRIES (models.countries)
* comapnyid - char 32
* taxid - char 32
* vatid - char 32
* about_us

make a migration and form for admin to be able to modify all of this information.

Update event model to have foreign key to organizer, e.g. we should be able to set organizer for event.

**Comment by mimmon** [comment]
I am aware that my last pull request is not yet finished because of missing tests, however, I will need a little help there. Meanwhile, I would like to take this one. Is it possible?

**Comment by ricco386** [comment]
sure, if you have a PR on review it is OK to start another. What I meant is not to start 3-4 and none of them have on review.

**Comment by ricco386** [comment]
PR has been merged. Thanks
