### ISSUE TITLE
List of countries contains errors

### ISSUE THREAD

**Issue by jangondol** [pyconsk/django-konfera#211]
`konfera/models/countries.py` contains "Yugoslavia" (a country that no longer exists) and "Cook Iislands" (apparent typo). Where does this list come from? It appears to be incorrect and should be updated.

Please note that I didn't check all countries, just noticed these two. It's possible that there are many more issues I did not notice. We should use an authoritative source for the list (and, ideally, quote the source straight in the code).

**Comment by mimmon** [comment]
I suggest we should follow ISO-3166 standard, namely ISO 3166-1 alpha-2.

**Comment by ZoltanOnody** [comment]
@jangondol what about https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements ?

**Comment by jangondol** [comment]
@ZoltanOnody That sounds good! This seems to be the official source: http://www.iso.org/iso/home/standards/country_codes.htm

**Comment by mimmon** [comment]
I'll take care of this (if nobody objects).

**Comment by ricco386** [comment]
@mimmon sure go ahead
