### ISSUE TITLE
Create volunteer registration view

### ISSUE THREAD

**Issue by ricco386** [pyconsk/django-konfera#22]
Create simple view (with form and template) that will allow register volunteers and store them in DB.

View is available only if ticket_type volunteer us defined, otherwise show 404

Predefined values:
type
status: requested

**Comment by kapucko** [comment]
I'm taking this one

**Comment by kapucko** [comment]
@ricco386 could you give me please more details on this? I'm a bit confused...

**Comment by ricco386** [comment]
@kapucko sure...

Idea is to create a view, with form that will create a ticket for volunteer. Once the volunteer submit the (valid) form all the details will be stored in DB.

So essentially it will be [ModelForm](https://docs.djangoproject.com/en/1.10/topics/forms/modelforms/) for Ticket model.

You will have to check if for particular even exists TicketType for volunteer (attendee_type field, we are currently missing see bug #70), and if it does render the form, if not show 404.

Form fields should be following:

title
first_name
last_name
email
phone
description

Once the form is stored, in model pre-generate this fields:
type: TicketType for volunteer
status: requested

**Comment by kapucko** [comment]
Thank you @ricco386 
But there is one more thing. In the Ticket model there is also FK to Order, so I need either to modify the model to allow blank/null this field or  to generate some dummy Order instance. Am I correct?

**Comment by ricco386** [comment]
@kapucko yes you are right. 

There should be logic in ticked model, once it is stored without order will generate one. So I would say, for now (while developing and testing), you can modify order to be blank/null (but do not commit into PR) and I have to create related issue, with regards automatically creating order if it is not set in ticket model. Once this related issue will be done it would fix also this issue (once you finish it).

**Comment by ricco386** [comment]
I have created related issue #75

**Comment by ricco386** [comment]
PR merged
