### ISSUE TITLE
Email templates handling

### ISSUE THREAD

**Issue by ricco386** [pyconsk/django-konfera#225]
Add ability to modify email templates easily. Currently we do have email template in settings.

Lets add new table, email_templates with following field:
name
template
html_template
counter

This way admin can easily modify email template, lets have a fixture that will pre-define the email templates. Existing email should be in this fixture. Update the current code to use this new feature.

**Comment by mimmon** [comment]
I'll do it.

**Comment by ricco386** [comment]
PR #229 merged. Thank you.
