### ISSUE TITLE
Show information about the ticket 

### ISSUE THREAD

**Issue by ZoltanOnody** [pyconsk/django-konfera#241]
We should show more information about the ticket itself on the "buying" page.

https://staging.pycon.sk/register/event/2017/ticket/d0d9f624-14b4-4d85-965b-619c9e53f225/

We could show the description and the ticket price.

**Comment by ricco386** [comment]
I agree we can show the same info (event the same styling) as on tickets page: https://staging.pycon.sk/2017/tickets/

**Comment by mimmon** [comment]
I can try this one. So should there be a radio/dropdown added to template to choose from available ticket types?

**Comment by ricco386** [comment]
No button at this page user already selected ticket type he wants, so just display the information about ticket

**Comment by mimmon** [comment]
Ok, I see - it was not clear to me as I only checked staging, on production it is quite obvious. Thank you, I'll do it.

**Comment by ricco386** [comment]
Sure, if you have any question just ask... Sometimes we just create an issue as a note what to do and might not be obvious for others :)

**Comment by ricco386** [comment]
PR has been merged. Thank you
