### ISSUE TITLE
Add photo to talk proposal

### ISSUE THREAD

**Issue by mimmon** [pyconsk/django-konfera#244]
Add optional ImageField to talk/cfp where photo of talk proponent can be uploaded.

**Comment by mimmon** [comment]
I will take this one.

**Comment by ricco386** [comment]
How are you doing with this issue? Do you need any help with it?

**Comment by mimmon** [comment]
Sorry, this week I was too busy, I plan to do it tomorrow. I've already checked how to do it. If I get stuck I will let you know so that the issue can be closed asap.

**Comment by ricco386** [comment]
Sure thing, no problem. I was just wondering about the status ;) Thank you for your effort I appreciate it.

**Comment by ricco386** [comment]
PR has been merged.
