### ISSUE TITLE
event clean method issue

### ISSUE THREAD

**Issue by ricco386** [pyconsk/django-konfera#248]
In current code of event clean method we can easily get an TypeError: unorderable types: NoneType() >= datetime.datetime()

Create new event and leave CfP not allowed and cfp_end empty system will raise an exception. Besides we will send this info to users, so make sure clean method is also called on save.

**Comment by mimmon** [comment]
I'll do it together with #245 as these bugs are related

**Comment by ricco386** [comment]
PR merged thank you.
