### ISSUE TITLE
Mention open licensing

### ISSUE THREAD

**Issue by jangondol** [pyconsk/django-konfera#283]
[Videos](https://www.youtube.com/channel/UC8Tzn82aG4zdvtqlrfsLgSA) from PyConSK 2016 were licensed under [CC-BY](https://creativecommons.org/licenses/by/4.0/) and I suggest that we make sure on the website that this will be the case for 2017 as well. Same thing for other submitted resources.

Possible formulation: *We believe in sharing and license code and content under open licenses. By submitting Content (such as conference talk proposals, images, etc.) to PyCon.SK, you represent and warrant that you have all necessary rights and authority to upload such Content and license it to the world under the Creative Commons Attribution 4.0 License (CC-BY 4.0). Videos from PyCon.SK will also be made available under CC-BY 4.0.*

One possible place to include this on the [CfP page](https://www.pycon.sk/2017/cfp/).

Any thoughts, suggestions?

**Comment by ricco386** [comment]
You are right, I have updated the text on the page. We do currently have a hack on the website to be able to haev this for with text. I ahe create new issue #286 for proper way to add this.
