### ISSUE TITLE
Consider making it easier to update content

### ISSUE THREAD

**Issue by jangondol** [pyconsk/django-konfera#284]
I just noticed a bug on our front page, instead of "We are pleased to announce the PyCon SK 2017" we should say "We are pleased to announce PyCon SK 2017" (without "the").

So I searched for the string and found it in `konfera/fixtures/test_data.json`. I assume that if I update this file, this will not be reflected on the site (because I think the real text that is rendered on the site is stored in the database). Correct?

Is there a way for non-admins to make suggestions to content and make it easy to update content while keeping track of it in version control? (For example, maybe using a flat-file back-end or something similar.) This way we could have pull requests for content (not just code), discussions around these changes, and so on.

**Comment by ricco386** [comment]
This is more issue with lack of documentation. 

Fixtures doesnt have to be loaded. Eg. in this case they even didnt contain the data you were looking for. Our fixture has only PyCon 2016, once it was loaded we update data in the DB. Even if the data would be in fixture and you did fix it there it would prevent only issue with next person loading the data to the DB. Django is using fixtures only for initial data, and even that is not recommended, you shall create a migration with data.

What you need to do is to login to admin, search for the event you found an error in description and correct it there. Eg. this is the easiest way possible to update content. Problem is that we do not have documentation so you couldnt know...

What you are suggesting is new functionality, and not sure if it is suitable for this project... django-konfera can be installed by anyone, and he probably wouldnt care about our events, so he doesnt load the fixture. He can always edit events in the DB, but accepting event updates from public via fixtures is not sufficient, he can have migration, but that would mean to have fork with migration that will never go to upstream.

Therefore the only option that I see is to have some kind of form (in frontend) that will show current DB content, ability to store in DB for anyone and not publish. Admin would afterwards approve and publish the content. I see several security threads in this model.

I am closing this issue as with current development resources we would focus on different things, also I dont think there is anything to develop here. Feel free to re-open if you think I am mistaken and please do a suggestion. I am creating new issue: #385 Add Documentation Project is useless for others without documentation!
