### ISSUE TITLE
Add ability ask questionaire

### ISSUE THREAD

**Issue by ricco386** [pyconsk/django-konfera#290]
We need to send out questions to users, like size of t-shirt, dietary requirements, etc... We need to way how to handle it, django-konfera has to be able solve it. There are several ways how to do it:

A. Find out an existing app that will handle this. In this case add hooks, that will handle this functionality and add documentation how to use it.

B. Develop functionality that will handle this requirements.

If we decide for option B. we can discuss in more  details.

**Comment by ZoltanOnody** [comment]
I vote for option A.

https://github.com/MarkusH/django-dynamic-forms seems fine. I think we should definitely use it. 

I'll integrate it to our app in a few day, the requirements are: 
- one attendee (=one ticket) should be able to vote only once (and should be able to edit his votes)
- voting should be closed after some date

right?

**Comment by ricco386** [comment]
@ZoltanOnody alright look good. Yes that are the requirements, and one questionnaire (=one ticket) can have multiple questions (also different types, text, checkbox, etc...)

**Comment by ricco386** [comment]
Closing. We are going to refactor #320
