### ISSUE TITLE
Create location model

### ISSUE THREAD

**Issue by ricco386** [pyconsk/django-konfera#3]
Create model file:

title: CharField, max=128
street: CharField, max=128
street2: CharField, max=128
city: CharField, max=128
postcode: CharField, max=12
state: CharField, max=128
capacity: IntegerField

Once finished, please cross the issue off in list stored at #1 Create initial DB models and migrations

**Comment by Benjji** [comment]
Robime na tejto issue - vlavo od vchodu do miestnosti - nesiahat! :)

**Comment by jangondol** [comment]
Resolved by #25
