### ISSUE TITLE
Add tests for models

### ISSUE THREAD

**Issue by ricco386** [pyconsk/django-konfera#37]
Once refactoring in bug #34 is in place add tests for all models to test string representation of the model.

**Comment by TomasHo** [comment]
Working on this. 
@ricco386 is this what you mean?
`self.assertNotEqual(object.__str__(), 'Order object')`

**Comment by ricco386** [comment]
@TomasHo almost...

```python
def test_string_representation(self):
        entry = Room(title="My entry title")
        self.assertEqual(str(entry), entry.title)
```

I have already assigned this issu to myself as I am also creating test directory (similar to models), but if you would like once structure is in place we can share the models who will do what...

If you could please do #10 and once done you can generate migration: #1 and we will have models ready and can start fiddle with views and templates...
