### ISSUE TITLE
Create sponsor model

### ISSUE THREAD

**Issue by ricco386** [pyconsk/django-konfera#4]
Create model file:

title: CharField, max=128
type: CHOICES, (platinum, golden, silver, bronze, other, django_girls)
logo: FileField
url: URLField
about_us: TextField
event: ForeignKey, #2 events table, NOT NULL

Once finished, please cross the issue off in list stored at #1 Create initial DB models and migrations

**Comment by kapucko** [comment]
I'm gonna work on this issue

**Comment by ricco386** [comment]
MR merged to master
