### ISSUE TITLE
Create speaker model 

### ISSUE THREAD

**Issue by ricco386** [pyconsk/django-konfera#5]
Create model file:

first_name: CharField, max=128
last_name: CharField, max=128
email: EmailField
phone: CharField, max=64
bio: TextField
url: URLField
social_url: URLField
country: CharField, max=64
sponsor: ForeignKey, #4 sponsors table, DEFAULT NULL

Once finished, please cross the issue off in list stored at #1 Create initial DB models and migrations

**Comment by richban** [comment]
Pracujem natom.

**Comment by ZoltanOnody** [comment]
close

**Comment by ricco386** [comment]
@richban @richban thank you guys, closing issue.
