### ISSUE TITLE
Create talk model

### ISSUE THREAD

**Issue by ricco386** [pyconsk/django-konfera#6]
Create model file:

title: CharField, max=256
abstract: TextField
type: CHOICES, (talk, workshop)
status: CHOICES, (cfp, draft, approved, rejected, withdrawn)
duration: CHOICES, (30, 45) 
primary_speaker: ForeignKey, #5 speaker table, NOT NULL
secondary_speaker: ForeignKey, #5 speaker table, DEFAULT NULL
event: ForeignKey, #2 events table, NOT NULL

Once finished, please cross the issue off in list stored at #1 Create initial DB models and migrations

**Comment by mimmon** [comment]
Finished and PR sent, sorry did not reference the issue
