### ISSUE TITLE
Update talk admin class

### ISSUE THREAD

**Issue by ricco386** [pyconsk/django-konfera#66]
Create TalkAdmin class than can do following:

* filter by: type, duration, status, event (try and add if you like this filter)
* list view, show fields: title, type, status, event, speaker (try and add if you like this filter)
* group form fields:
  * description: title, abstract, evet
  * details: type, status, duration, speakers

any other improvements, welcome...

**Comment by Redpoint1** [comment]
working on it

**Comment by ricco386** [comment]
PR merged. Thanks.
