### ISSUE TITLE
Update sponsor admin class

### ISSUE THREAD

**Issue by ricco386** [pyconsk/django-konfera#69]
Create SponsorAdmin class than can do following:

* list view, show fields: title, type, url
* group form fields:
   *  details: all fields can be here...
   *  events: list of events where is sponsoring
   *  soeakers: list of speakers that shopsor had

any other improvements, welcome...

**Comment by Redpoint1** [comment]
working on it

**Comment by ricco386** [comment]
@Redpoint1 thanks
