### ISSUE TITLE
Create schedule model

### ISSUE THREAD

**Issue by ricco386** [pyconsk/django-konfera#7]
Create model file:

start: DateTimeField,
description: CharField, max=128
talk: ForeignKey, #6 talk table, NOT NULL
duration: IntegerField
room: ForeignKey, #8 room table, DEFAULT NULL

Once finished, please cross the issue off in list stored at #1 Create initial DB models and migrations

**Comment by TomasHo** [comment]
working on it

**Comment by ricco386** [comment]
MR merged into master
