### ISSUE TITLE
Update ticket model save logic

### ISSUE THREAD

**Issue by ricco386** [pyconsk/django-konfera#75]
Once ticket is created and stored in DB order should be automatically generated if it is not part of the ticket.

Create [save()](https://docs.djangoproject.com/en/1.10/topics/db/models/#overriding-predefined-model-methods) method that will check if order is not set and if so, create new order. Set status to awaiting_payment, price is copied from ticket type, and discount is calculated from percentage if discount it set.

**Comment by kapucko** [comment]
I'm taking also this one.

**Comment by SvetlanaM** [comment]
pre_save and post_save signals are also good https://docs.djangoproject.com/en/1.10/topics/signals/ on this

**Comment by ricco386** [comment]
PR merged
