### ISSUE TITLE
Update order model

### ISSUE THREAD

**Issue by ricco386** [pyconsk/django-konfera#76]
In order model we should set purchase date uppon creation so it can have auto_add_now.

Create [save()](https://docs.djangoproject.com/en/1.10/topics/db/models/#overriding-predefined-model-methods) method that will check the status of order and if status changes to paid generate the datetime for payment_date.

**Comment by ZoltanOnody** [comment]
I'll do it

**Comment by ricco386** [comment]
PR merged to master.

Thnak you.
