### ISSUE TITLE
Consider renaming the project

### ISSUE THREAD

**Issue by jangondol** [pyconsk/django-konfera#77]
The project is currently called `django-konfera`. It has a Slovak name (with Slovak spelling) yet its code and issues are in English. Are we going to keep it this way? Would it not be better to translate the name to English as well (especially since we are making a reusable project)?

Possible name: `django-conference` (it is available on PyPi, while `django-events` is [taken](https://pypi.python.org/pypi/django-events)), or suggest your own.

We can keep `django-konfera` if this is what we agree on but I think it should be a conscious decision. Any thoughts?

**Comment by ricco386** [comment]
Me 5cents to this question:

* we have this project in English because it doesn't make sense to do open source project in other language. Even if there are typos, and mistakes in text any programmer could come and pick up on this project, if it was in Slovak he wouldn't be able to...
* the name was picked up that it wouldn't be "too official" and people would understand, how ever that was target to people at Bratislava meetup.
* there is a lot of popular projects with weird names, so we might sound weird to non Slovak speaking people, however (this is question) is there any background similarity (with English word conference), sound, pronunciation, etc...? What I mean is that if English person would hear the name he would know that is is not English word, or correct word, but sounds like that it has something to do with conference?
* @jangondol what is some slang word for conference?

I don't mind if we rename it since we are in very early stage... Unfortunately I am not able to suggest better name... So I suggest if anyone has an idea of the name, please share you thoughts.

I think at the end majority of contributors will decide, so please write you opinion in this matter.

**Comment by ZoltanOnody** [comment]
I like the name `django-konfera` because it doesn't sound official. If it was called `django-conference` I'd probably think it has something to do with *DjangoCon* or some other conference about *Django*.
 
The project is mainly design for *PyconSK* and *Python meetups in Bratislava* so I think it can have at least one thing in Slovak; the name.

**Comment by jangondol** [comment]
@ZoltanOnody Yeah, I understand. If we keep the app mostly for us, this totally makes sense.

In the meanwhile, it seems that this app could be actually quite useful for PyCon conferences elsewhere and even for "non-PyCon" conferences. I haven't found many good options for Django (at least not up-to-date ones).

So, if you think this could be useful for people other than us (and since we're developing this as a reusable app, it seems that this is the case), it might be useful to make this **more easily discoverable**. That means a name + description that contains keywords that people might be searching for (like `django-conference`, `django-eventmanagement`), etc.

I like how `django-konfera` sounds: it feels relaxed and non-official. At the same time, I think that while it might sound cool to the Slovak speakers, "konfera" probably makes little sense to those who do not speak Slovak (which is 99+ percent of the internet / our target group). Plus it invites typos: English speakers may type "confera".

@ricco386 Unsure about slang words, here are [some synonyms](http://www.thesaurus.com/browse/conference).

**Comment by TomasHo** [comment]
I'm leaning to the idea of renaming it. Let's thing BIG ;) What about these names?
`eventizer`, `djangovent`
Exciting exercise :)

**Comment by ZoltanOnody** [comment]
What about django-confera? :)

**Comment by TomasHo** [comment]
What other packages with a dash do you use? ;)

**Comment by ZoltanOnody** [comment]
I run `pip freeze | grep -e ".-."` in one of the projects I am working on:

    diff-match-patch==20121119
    django-autoslug==1.9.3
    django-bootstrap-form==3.2.1
    django-braces==1.9.0
    django-bulk-update==1.1.10
    django-classy-tags==0.7.2
    django-contact-form==1.2
    django-contrib-comments==1.7.1
    django-cors-headers==1.1.0
    django-crispy-forms==1.6.0
    django-debug-toolbar==1.4
    django-dotenv==1.4.1
    django-easy-select2==1.3.2
    django-favicon==0.1.2
    django-import-export==0.4.5
    django-mathfilters==0.4.0
    django-mptt==0.8.4
    django-nyt==0.9.9
    django-oauth-toolkit==0.10.0
    django-sekizai==0.9.0
    django-sendfile==0.3.10
    django-sortedm2m==1.3.0
    django-tag-parser==2.1
    django-taggit==0.20.0
    django-threadedcomments==1.0.1
    fake-factory==0.5.7
    ndg-httpsclient==0.4.1
    pip-tools==1.6.5
    pkg-resources==0.0.0
    pymdown-extensions==1.1
    python-dateutil==2.5.3
    python-openid==2.2.5
    python-social-auth==0.2.19
    requests-oauthlib==0.6.1
    sorl-thumbnail==12.3

So I don't think it would be a problem.

**Comment by jangondol** [comment]
@TomasHo `django-eventizer` sounds fun... :-) (And yes, prepending the name with `django-` helps discoverability).

@ZoltanOnody The name [Confera](https://www.google.com/search?q=confera) may be trademarked and therefore potentially risky to use. But it's definitely an interesting combination of English and Slovak! ;-)

To be honest, I am currently tempted by `django-conference` at the moment and its availability on PyPi. By making the name generic enough, this project could take off well beyond Slovak borders. But let's sleep on it, renaming can wait a few days. Also, `django-eventizer` is unique, not bad at all!

Any *other* suggestions? Keep sending them!

**Comment by mimmon** [comment]
django-confy?

Dňa 18.9.2016 17:33 používateľ "Jan Gondol" <notifications@github.com>
napísal:

**Comment by ricco386** [comment]
@ZoltanOnody in the afternoon I was thinking just the same, lets switch k to c and use django-confera... @jangondol I wouldn't be worried about trademark as most likely we find some service or company with such name all the time, besides event if we got into trouble we rename product and start writing blogs about it and will have much more publicity 😆 ... 

From google search:
* confera - some group in US, some company in DE, some old zoho product and last name of some person 😄 so it seems quite frequented...
* eventizer - there is already service eventizer, and company in finland
* confy - software, food for babies, etc...

I think if we will to a static page to the software and pick up correct wording (to have SEO for conference, confera, etc.) we can leave it as it is now, and here is the explanation:

> Replacing "c" with "k" was at the centre of a Monty Python joke from the Travel Agent sketch. Eric Idle has an affliction that makes him pronounce the letter C as a B, as in "bolour" instead of "colour." Michael Palin asks him if he can say the letter K? Idle replies that he can, and Palin suggests that he spell words with a K instead of C. Idle replies, "what, spell bolour with a K? Kolour. Oh! I never thought of that before! What a silly bunt!"

https://www.youtube.com/watch?v=Yz2LaJOVAiA

We still have time to decide on this until we release 0.1 which is scheduled 30.9. 😄 however you guys are doing great job so we might even have it earlier, but still plenty time to think about the name...

**Comment by jangondol** [comment]
@ricco386 Good catch, `django-eventizer` is off the hook then.

BTW, I just discovered that [django-conference](https://bitbucket.org/hssonline/django-conference) already exists elsewhere. So although it is not on PyPI, we should probably consider something else to avoid confusion. And add it to the README as a possible alternative... ;-)

Speaking of playful names, other possible options include `django-confetti`, `django-eventual`, `django-confman` (meaning *conference management*, not "conference man").

More brainstorming welcome!

**Comment by jangondol** [comment]
`django-confero` ("Náš spolužiak Fero...") :wink:

FYI: globally unique name, so it would be easy to find & track its usage via Google...

**Comment by TomasHo** [comment]
Booooo, sexism in IT on full display. What about all those Františka-s that you might offend ?? :)

Apart from that joke - `django-conferp` sounds fine to me

**Comment by ZoltanOnody** [comment]
Honestly, I wouldn't know what does the app do just from `django-confero`. Now I realized that probably it's the same with `django-konfera` for non-Slovak speakers.

**Comment by jangondol** [comment]
@ZoltanOnody `django-confmgmt`? :wink:

**Comment by ricco386** [comment]
OK, i think it is time to decide. Please write down the name you like. At 30th I will do the release and by that time we have to decide, rename and update the code, where necessary...

**Comment by ricco386** [comment]
I vote to leave the package name as it is now.

**django-konfera** - I have described my reasons in a comment above.

**Comment by jangondol** [comment]
My vote: **`django-confero`**. Similar to django-konfera, *easier to spell for non-Slovaks* (also "django" and "confero" kind of rhyme).

**Comment by ZoltanOnody** [comment]
I vote to leave it as it is - **django-konfera**

**Comment by TomasHo** [comment]
I vote for **`django-confero`**

**Comment by jangondol** [comment]
At this moment we have a tie: two votes for `django-konfera` and two votes for `django-confero`. If no other votes come in, we need to find a mechanism how to decide. The simple solution is to leave this "as is" (and perhaps revisit the issue in the future in case more consensus builds up or if there is a need). Also, @ZoltanOnody and @ricco386 made more contributions to this project than me, so if this remains a tie, I give my vote to them.

**Comment by ZoltanOnody** [comment]
I suggest to let's wait for the meetup and vote there. Of course the votes here will be counted as well, in case someone cannot make it to the meetup.

**Comment by kapucko** [comment]
I think that sometime the first idea is the best one. So I would vote to leave it as is.

**Comment by jangondol** [comment]
Vote results at the meetup: 5 votes for `django-konfera`, 5 votes for `django-confero` (aaargh!). To resolve the tie, @ricco386 decided that he would have two votes, so the new vote results are 6 to 5 and the package name remains `django-konfera`... :-)
