### ISSUE TITLE
Create room model

### ISSUE THREAD

**Issue by ricco386** [pyconsk/django-konfera#8]
Create model file:

title: CharField, max=128

Once finished, please cross the issue off in list stored at #1 Create initial DB models and migrations

**Comment by andynet** [comment]
andynet: I'm working on this

**Comment by ZoltanOnody** [comment]
done in https://github.com/pyconsk/django-konfera/pull/27 close it

**Comment by ricco386** [comment]
@andynet @ZoltanOnody thank you guys, closing the issue.
