### ISSUE TITLE
Create DiscountCodeAdmin class

### ISSUE THREAD

**Issue by ricco386** [pyconsk/django-konfera#83]
Create DiscountCodeAdmin class than can do following:

* list view, show fields: title, discount, ticket_type, usage
* group form fields:
  * details: title, usage, hash
  * discount: discount, usage
  * availabilty: date_from, date_to

any other improvements, welcome... Suggestion, add function that return status of discount: not available yet, active, expired depending on current datetime and values defined in model instance. You can add this to admin view. If you create such function, add test for it...

**Comment by ZoltanOnody** [comment]
done in #106
