### ISSUE TITLE
Create TicketTypeAdmin class

### ISSUE THREAD

**Issue by ricco386** [pyconsk/django-konfera#84]
Create TicketTypeAdmin class than can do following:

* filter by: attendee_type
* list view, show fields: title, price, attendee_type, event
* group form fields:
  * details: title, description, price, attendee_type, event
  * availabilty: date_from, date_to

any other improvements, welcome... 

Suggestion, add function that return status of ticket type: not available yet, active, expired depending on current datetime and values defined in model instance. You can add this to admin view. If you create such function, add test for it.

**Comment by kisso** [comment]
I am working on it.

**Comment by kisso** [comment]
Should the status depends only on time?

**Comment by ricco386** [comment]
@kisso yes for now it is sufficient that status is generated by the time compared with from to dates. In the future if we found a use case for different behavior we will refactor.
