### ISSUE TITLE
Create ticket_type model

### ISSUE THREAD

**Issue by ricco386** [pyconsk/django-konfera#9]
Create model file:

title: CharField, max=128
description: TextField
price: DecimalField
available_from: DateTimeField
available_to: DateTimeField
event: ForeignKey, #2 events table, NOT NULL

Once finished, please cross the issue off in list stored at #1 Create initial DB models and migrations

**Comment by TomasHo** [comment]
Working on this

**Comment by ZoltanOnody** [comment]
done in https://github.com/pyconsk/django-konfera/pull/30 close it

**Comment by ricco386** [comment]
@TomasHo @ZoltanOnody thank you guys closing the issue.
