### ISSUE TITLE
Add ability to process FIO bank transfers

### ISSUE THREAD

**Issue by ricco386** [pyconsk/django-konfera#98]
FIO bank has API that allows to download transactions statement: http://www.fio.sk/docs/cz/API_Bankovnictvi.pdf

Create a view that can be called by cron every X hours (lets assume 24) and will download transactions and compare them with orders. Each order has to have its own unique numeric ID, this ID is presented to user and he can select bank transfer as a payment method.

We need to go through transactions from the bank and if we find a match of variable symbol and order ID we change the status of the order to PAID.

Talk to me (@RicCo386) about the token for testing.

**Comment by ZoltanOnody** [comment]
I'll do it.

**Comment by jangondol** [comment]
Consider using an external app for this (see [django-fiobank](https://pypi.python.org/pypi/django_fiobank)) or handling payments in a more abstract way. `django-konfera` is getting pretty big and if we start integrating banks *directly*, reuse by others may become difficult.

**Comment by ricco386** [comment]
I agree with @jangondol that if we want to have reusable app this could go into separate app and we shall build hooks in order so we can connect any type of payment provider.

However, I have create this issue as something more difficult for experienced person so he doesnt have to work with simple tasks, and he can leave the simple tasks to other less experienced. So in this case I dont mind if @ZoltanOnody will create his directory with urls, views, etc. and do the logic there: at the moment one view that will be called periodically. Later we can re-factor and move it to separate app if necessary (this task is quite ahead of the development at this moment). If more people should work on this we can not separate everything at this point as it will be pain to get them all on board.

OK so lets do it properly (at least easy to refactor properly) and I am thinking about signals: 
 * Create directory payments, inside django-konfera
 * Create signals.py where we will collect all signal handlers
 * Create new view: /payments/check that will emit signal, in this signal we can have query of all orders that shall be checked (we need to have a thought about this bit)
 * Create fio.py what will receive signal and process all orders

If we do it like this anyone can write his own signal receiver and connect any type of processing, at the same time we can easily refactor fio (or whole payments) into separate app. This is just an initial suggestion, please feel free to come up with better one. I need to sleep about this and have a thought if this is correct (for now it is just info for @ZoltanOnody what way we might go with this).

**Comment by ricco386** [comment]
PR merged, with sync functionality. We might improove in future, but separate issue will be created for it.
